site_name: RISC-V MACHINES Documentation
site_description: Guides and information for making Kubernetes, Linux and applications run on RISC-V powered machines.

nav:
  - 'Home': 'index.md'
  - 'Linux':
    - 'Linux on RISC-V using QEMU and BUSYBOX from scratch': 'linux/simple.md'
  - 'About':
    - 'Authors': 'about.md#authors'
    - 'License': 'about.md#license'

nav_style: dark

theme:
    name: material
    highlightjs: true

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
