site_name: RISC-V MACHINES Documentation
site_description: Guides and information for making Kubernetes, Linux and applications run on RISC-V powered machines.

nav:
  - Home: index.md
  - About: about.md
     - Authors: about.md#authors
     - License: about.md#license

nav_style: dark

theme:
    name: readthedocs
    highlightjs: true
