site_name: RISC-V MACHINES Documentation
site_description: Guides and information for making Kubernetes, Linux and applications run on RISC-V powered machines.

nav:
  - 'Home': 'index.md'
  - 'Linux':
    - 'Linux on RISC-V using QEMU and BUSYBOX from scratch': 'linux/simple.md'
    - 'Podman for RISCV64' : 'linux/podman.md'
    - 'Fedora 33 Base Image for RISC-V' : 'linux/f33-scratch.md'
    - 'Fedora Core OS on RISC-V' : 'linux/core-os.md'
  - 'About':
    - 'The Project': 'about.md'
    - 'Authors': 'about.md#authors'
    - 'License': 'about.md#license'

nav_style: dark

theme:
    name: material
    palette:
      scheme: slate
    highlightjs: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rv-machines/documentation

copyright: GPL-3.0 License (ɔ) 2021 — <a href="https://github.com/NassimBounouas">Nassim BOUNOUAS</a> & <a href="https://github.com/nirousseau">Nikita ROUSSEAU</a>

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.keys